import json
import re

class ComplianceParser:
    """
    Validates and sanitizes structured inputs generated by LLM autonomous agents,
    ensuring all credits, actions, and predictions conform to market requirements.
    """

    def extract_json(self, text):
        """
        Robustly extracts JSON structures from LLM text responses, 
        even if wrapped in markdown blocks or surrounded by commentary.
        """
        if not isinstance(text, str):
            return None

        # Clean markdown code blocks if present
        cleaned = re.sub(r"```json\s*", "", text)
        cleaned = re.sub(r"```\s*", "", cleaned)
        cleaned = cleaned.strip()

        # Find first '{' and last '}'
        try:
            start_idx = cleaned.index('{')
            end_idx = cleaned.rindex('}')
            json_str = cleaned[start_idx:end_idx + 1]
            return json.loads(json_str)
        except (ValueError, json.JSONDecodeError):
            # Fallback regex search
            match = re.search(r"(\{.*\})", cleaned, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group(1))
                except json.JSONDecodeError:
                    pass
            return None

    def validate_credit_request(self, response_text, max_loan):
        """
        Validates loan credit requests from agents.
        Returns: (is_valid, error_msg, formatted_data)
        """
        data = self.extract_json(response_text)
        if not data:
            return False, "Could not extract a valid JSON block from your response. Ensure you output standard JSON wrapped in curly braces.", None

        if "loan" not in data:
            return False, "Required key 'loan' is missing from the JSON.", None

        decision = str(data["loan"]).strip().lower()
        if decision not in ["yes", "no"]:
            return False, "Value of 'loan' must be either 'yes' or 'no'.", None

        if decision == "no":
            # Sanitize and return
            return True, "", {"loan": "no"}

        # Validate loan parameters
        if "loan_type" not in data or "amount" not in data:
            return False, "When 'loan' is 'yes', you must provide both 'loan_type' and 'amount'.", None

        try:
            loan_type = int(data["loan_type"])
            if loan_type not in [0, 1, 2]:
                return False, "The 'loan_type' must be an integer: 0 (22-day), 1 (44-day), or 2 (66-day).", None
        except (ValueError, TypeError):
            return False, "The 'loan_type' must be a valid integer (0, 1, or 2).", None

        try:
            amount = float(data["amount"])
            if amount <= 0:
                return False, "Borrowing 'amount' must be a positive number.", None
            if amount > max_loan:
                return False, f"Your credit request of ${amount:.2f} exceeds your borrowing capacity limit of ${max_loan:.2f}.", None
        except (ValueError, TypeError):
            return False, "The 'amount' must be a valid positive number.", None

        return True, "", {
            "loan": "yes",
            "loan_type": loan_type,
            "amount": amount
        }

    def validate_market_order(self, response_text, cash, holding_a, holding_b, price_a, price_b):
        """
        Validates trading orders from agents against cash and inventory limits.
        Returns: (is_valid, error_msg, formatted_data)
        """
        data = self.extract_json(response_text)
        if not data:
            return False, "Could not extract a valid JSON block from your response. Format must be { ... }.", None

        if "action_type" not in data:
            return False, "Required key 'action_type' is missing.", None

        action = str(data["action_type"]).strip().lower()
        if action not in ["buy", "sell", "no"]:
            return False, "The value of 'action_type' must be 'buy', 'sell', or 'no'.", None

        if action == "no":
            return True, "", {"action_type": "no"}

        if "stock" not in data or "amount" not in data or "price" not in data:
            return False, "When submitting an order, you must provide 'stock', 'amount', and 'price'.", None

        ticker = str(data["stock"]).strip().upper()
        if ticker not in ["A", "B"]:
            return False, "The target 'stock' ticker must be either 'A' or 'B'.", None

        try:
            amount = int(data["amount"])
            if amount <= 0:
                return False, "The order 'amount' must be a positive integer.", None
        except (ValueError, TypeError):
            return False, "The order 'amount' must be a valid positive integer.", None

        try:
            price = float(data["price"])
            if price <= 0:
                return False, "The order limit 'price' must be a positive number.", None
        except (ValueError, TypeError):
            return False, "The order limit 'price' must be a valid positive number.", None

        # Position Compliance Check
        total_cost = amount * price
        if action == "buy":
            if total_cost > cash:
                return False, f"Insolvency Risk: Order value (${total_cost:.2f}) exceeds your available cash balance (${cash:.2f}). Please reduce amount or price.", None

        if action == "sell":
            available_inventory = holding_a if ticker == "A" else holding_b
            if amount > available_inventory:
                return False, f"Short-selling is disabled. You cannot sell {amount} shares because you only hold {available_inventory} shares of Stock {ticker}.", None

        return True, "", {
            "action_type": action,
            "stock": ticker,
            "amount": amount,
            "price": price
        }

    def validate_forecast(self, response_text):
        """
        Validates directional estimates from agents.
        Returns: (is_valid, error_msg, formatted_data)
        """
        data = self.extract_json(response_text)
        if not data:
            return False, "Could not extract a valid JSON block from your response.", None

        keys = ["buy_A", "buy_B", "sell_A", "sell_B", "loan"]
        missing = [k for k in keys if k not in data]
        if missing:
            return False, f"Required keys {missing} are missing from the forecasting JSON.", None

        for k in keys:
            val = str(data[k]).strip().lower()
            if val not in ["yes", "no"]:
                return False, f"Value of key '{k}' must be 'yes' or 'no'. Got '{val}' instead.", None
            data[k] = val

        return True, "", data
